openapi: 3.0.1
info:
  title: Todo-Listen-API
  version: 1.0.0
  description:
    Diese REST-API ermöglicht das Erstellen, Bearbeiten und Löschen
    von Todo-Listen und Einträgen.
  contact:
    email: s.tiemann@basecom.de
    url: https://github.com/stiemannbscm/OpenAPI
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://127.0.0.1:5000/

paths:
  /todo-lists:
    get:
      summary: Gibt alle Todo-Listen zurück
      responses:
        '200':
          description: Liste aller Todo-Listen
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoList'
        '500':
          $ref: '#/components/responses/InternalError'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'

  /todo-list:
    post:
      summary: Neue Todo-Liste hinzufügen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Liste erfolgreich erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'

  /todo-list/{list_id}:
    get:
      summary: Gibt eine bestimmte Liste zurück
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Liste gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'

    delete:
      summary: Löscht eine komplette Todo-Liste
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/SuccessDelete'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'

  /todo-list/{list_id}/entries:
    get:
      summary: Gibt alle Einträge einer Liste zurück
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Einträge erfolgreich geladen
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'

  /todo-list/{list_id}/entry:
    post:
      summary: Fügt neuen Eintrag in eine Liste ein
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Eintrag erfolgreich erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'

  /todo-list/{list_id}/entry/{entry_id}:
    put:
      summary: Aktualisiert einen bestehenden Eintrag
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
        - in: path
          name: entry_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Eintrag erfolgreich aktualisiert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'

    delete:
      summary: Löscht einen Eintrag aus einer Liste
      parameters:
        - in: path
          name: list_id
          required: true
          schema:
            type: string
        - in: path
          name: entry_id
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/SuccessDelete'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'

components:
  responses:
    NotFound:
      description: Ressource nicht gefunden
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    BadRequest:
      description: Fehlerhafte Anfrage
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    InternalError:
      description: Interner Serverfehler
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    MethodNotAllowed:
      description: Methode nicht erlaubt
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    SuccessDelete:
      description: Erfolgreich gelöscht
      content:
        application/json:
          schema:
            type: object
            properties:
              msg:
                type: string

  schemas:
    TodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    TodoEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        list_id:
          type: string
          format: uuid
